### ISSUE TITLE
Desenvolver o Backend

### ISSUE THREAD

**Issue by IanFPFerreira** [UnBArqDsw2021-2/2021.2_G3_stag.io_Backend#1]
Desenvolver a modelagem física do banco de dados e API de conexão com o frontend.

**Comment by italovinicius18** [comment]
Api desenvolvida com sucesso!

Utilizamos a ferramenta Insomnia para criar as requisições HTTP e assim simulamos o CRUD no banco de dados com as ações que necessitamos.

Fizemos o deploy do código em JS na plataforma do Heroku e assim conseguimos testas que as alterações e manipulações eram feitas no banco de dados da Azure.
